export const cardsData = [
  {
    id: 1,
    title: "Task 1",
    datetime: "24/1/2022 16:40 hs",
    creator: "Lucas Belich",
    description: "Desc 1",
    type: "Nueva",
    priority: "Alta",
  },
  {
    id: 2,
    title: "Task 2",
    datetime: "24/1/2022 16:40 hs",
    creator: "Lucas Belich",
    description: "Desc 2",
    type: "En proceso",
    priority: "Alta",
  },
  {
    id: 3,
    title: "Task 3",
    datetime: "24/1/2022 16:40 hs",
    creator: "Lucas Belich",
    description: "Desc 3",
    type: "Finalizada",
    priority: "Media",
  },
  {
    id: 4,
    title: "Task 4",
    datetime: "24/1/2022 16:40 hs",
    creator: "Lucas Belich",
    description: "Desc 4",
    type: "Nueva",
    priority: "Media",
  },
  {
    id: 5,
    title: "Task 5",
    datetime: "24/1/2022 16:40 hs",
    creator: "Lucas Belich",
    description: "Desc 5",
    type: "Nueva",
    priority: "Alta",
  },
  {
    id: 6,
    title: "Task 6",
    datetime: "24/1/2022 16:40 hs",
    creator: "Lucas Belich",
    description: "Desc 6",
    type: "Nueva",
    priority: "Alta",
  },
];
